### ISSUE TITLE
setup-ssb-db script seems to have hardcoded scale factor

### ISSUE THREAD

**Issue by leibatt** [eyalroz/ssb-tools#1]
Even when I change the scale factor parameter, dbgen is executed with scale factor 1. This code seems to be the issue in the script:
https://github.com/eyalroz/ssb-tools/blob/0e7c1da7a6747bd7511db97f84c1bef53a32ce2e/scripts/setup-ssb-db#L425

**Comment by eyalroz** [comment]
Oh, how stupid of me... don't know how that happened. Will get right to it. Sorry!

**Comment by eyalroz** [comment]
@leibatt : Please check whether this fix works for you as well.
